### ISSUE TITLE
Error with Anki 2.1.20 Beta 5

### ISSUE THREAD

**Issue by Kosezu** [lovac42/Cardistry#6]
When loading 'Cardistry Dynamically Adjust New Cards':
Traceback (most recent call last):
  File "aqt/addons.py", line 192, in loadAddons
  File "/Users/csosborn/Library/Application Support/Anki2/addons21/1535078906/__init__.py", line 1, in <module>
    from . import cardistry
  File "/Users/csosborn/Library/Application Support/Anki2/addons21/1535078906/cardistry.py", line 67, in <module>
    oldSync=anki.sync.Syncer.sync
AttributeError: module 'anki' has no attribute 'sync'

**Comment by lovac42** [comment]
The latest update seems to be working fine, so I am closing this. Open this again or file another ticket if you run into any problems.
